name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/sitkoru/php7-ci:$GITHUB_SHA
    - name: Tag as latest
      if: github.ref == 'refs/heads/master'
      run: docker tag docker.pkg.github.com/sitkoru/php7-ci:$GITHUB_SHA docker.pkg.github.com/sitkoru/php7-ci:latest
    - name: Docker login
      run: docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Docker push tag
      run: docker push docker.pkg.github.com/sitkoru/php7-ci:$GITHUB_SHA
    - name: Docker push latest
      if: github.ref == 'refs/heads/master'
      run: docker push docker.pkg.github.com/sitkoru/php7-ci:latest
